# Generated by Django 5.2.4 on 2025-07-09 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_customer_membersip'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection1')
             """, """
            DELETE FROM store_collection
            WHERE title='collection1'
            """)
    ]
