# Generated by Django 5.2.4 on 2025-07-09 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20250709_0942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='membersip',
            new_name='membership',
        ),
    ]
