# Generated by Django 5.2.4 on 2025-07-09 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_membersip_customer_membership'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='unite_price',
            new_name='unit_price',
        ),
    ]
