# Generated by Django 4.2.23 on 2025-07-23 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='store/dog2.jpeg', upload_to='store/images'),
        ),
    ]
