# Generated by Django 4.2.23 on 2025-07-29 10:20

from django.db import migrations, models
import store.validators


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='store/dog2.jpeg', upload_to='store/images', validators=[store.validators.validate_file_size]),
        ),
    ]
